name: Run NumPy Practice

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install numpy jupyter nbconvert

    - name: Run notebooks
      run: |
        jupyter nbconvert --to notebook --execute --inplace *.ipynb
